- README.md
Correct spelling and fix `Persistence` section "jump to" link
> Fix Persistence section anchor link

- README.md
Kotlin should also be considered when talking about Android :)
> adding Kotlin

- README.md
Changed all "android" occurrences to "Android".
> Normalized Android occurrences

- README.md
Add HockeyApp in Crash Reporting
> Add HockeyApp in Crash Reporting

- README.md
Added GSON and Moshi Library used in Serialization and Deserialization of JSON in the Utilities Section.
> Added JSON Serialization and Deserialization Library in Utilities Section

- README.md
Removed trailing slashes. HTTPS in URLs when possible. Fixed typos.
> Removed trailing slashes. HTTPS in URLs when possible. Fixed typos.

- README.md
> Add RxAndroid library

- README.md
This library, would be a great fit for image processing which allows users to download images either unencrypted or encrypted, given that you have the key when it comes to encrypted and allows users to crop, resize, create circular image and change the format.
> Adding pollexor library under image processing

- README.md
Thanks for such an awesome list
> Added Android Developers Backstage podcast and Android for iOS developer book

- README.md
> Added RxBinding in the Utilities(Advanced)

- README.md
The JetBrains Markdown editor kinda sucks and this one is way better. 😄
> Add Markdown Navigator 2.0 to the list

- README.md
I'll be upfront on this one, I'm the main dev for Robot Scouter so if this is crossing the line, that's fine. However, I think Robot Scouter has some really cool features that are useful for other devs to look at:
- [Completely automated Play Store publishing](https://github.com/SUPERCILEX/Robot-Scouter/blob/master/build.sh#L3-L12)
- [Tight integration with Firebase libraries](https://github.com/SUPERCILEX/Robot-Scouter/blob/master/app/build.gradle#L83-L103) and [custom builds of FirebaseUI](https://github.com/SUPERCILEX/FirebaseUI-Android) (I'm always [pushing back upstream](https://github.com/firebase/FirebaseUI-Android/graphs/contributors?from=2015-07-12&to=2017-05-04&type=a), but it can take some time for new releases to come out)
- [Really advanced spreadsheet …
> Add Robot Scouter to the list

- README.md
I've added [Conversations](https://github.com/siacs/conversations)
> Add Conversations in Open Source apps

- README.md
JazzyViewPager provide a Custom View Pager with the template of the page transform to be added in the view pager which provide a beautiful  ui components for the android. So it will be good to add in the List.
> Added JazzyViewPager Library to Ui Components

- README.md
[BottomBar](https://github.com/roughike/BottomBar) - A custom view component that mimics the Material Design Bottom Navigation pattern
> Add Bottom Bar to UI Components

- README.md
[FastHub](https://github.com/k0shk0sh/FastHub) - GitHub client for Android
> Add FastHub to Open-Source Apps

- README.md
Exoplayer provide an extensible version of the  Media Player which can be added in the application to support various feature to make an Advanced Media Player. It has been used by the Application like **MxPlayer** as a base of their application.
> Added Exoplayer in the UI Components

- README.md
Matisse  provide an UI Component to add a picker to choose multiple file for the application to upload and share between the user .
> Added Matisse in UI Components

- README.md
2048 is an awesome open source android game which have an a million download on the play store.
> Added 2048 in Open Source Games

- README.md
Kotlin Poet is an open source library created by the Square to generate kt extension source file
> Added Kotlin Poet in the Kotlin Library

- README.md
Java Poet is Java API Library to generate the .JAVA source file dynamically  which help in doing process like annotation processing or interacting with meta data files (e.g., database schema, protocol formats).
> Added JavaPoet to Utilities(Advanced) of Java Section

- README.md
CropIwa - library which is highly configurable for image cropping.
Alerter - This library aims to overcome the limitations of Toast and Snackbar, while reducing the complexity of your layouts.
> Cropiwa, Alerter

- README.md
Added Firebase Crash Reporting library in crash reporting and tracking category.
> Added Firebase Crash Reporting library.

- README.md
This Library Provide a Memory Efficient Shimmer Effect While Loading the Data from the External Source by creating a shimmering effect which is common in now most of the web technology.
> Added ShimmerLayout in UI Utilities

- README.md
Since the Kotlin is now a official language for the android development, **Android Development with Kotlin** provide a medium to learn the **Kotlin** in an efficient way to write better quality code and ease in development in android platform.
> Added Android Development with Kotlin in Book Section

- README.md
Remixer is a framework to iterate quickly on UI changes by allowing us to adjust UI variables without needing to rebuild (or even restart) our app.
> Added Remixer to the UI Library

- README.md
This new link would be really helpful for developers looking for an API for a specific purpose.
> Added 4 new links

- README.md
- AndroidPub was mentioned 2 times.
> Removed duplicate site

- README.md
> Addition in site

- README.md
Update Instabug sponsorship listing
• Modify content
• Modify picture
• Modify URL
> Update Instabug listing
